apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-05-21T03:53:11Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31548
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
